import { useEffect, useMemo, useRef, useState } from 'react';
import { Cuboid, Flag, Globe2, Search, SlidersHorizontal, X } from 'lucide-react';
import { t, useLanguage } from '../i18n';
import { getEditorial } from '../i18n/editorial';
import { formatMetres } from '../domain/measurements.mjs';
import type { ModelCase } from '../domain/catalog';
import './model-gallery.css';
import TowerFilterFields from './TowerFilterFields';
import { DEFAULT_TOWER_FILTERS, activeTowerFilters, type TowerFilters } from '../domain/tower-filters';
export default function ModelGallery({ cases, mappedCount, filters, onFilters, onExplore, onPreview, onHelp, onClose }: {cases:ModelCase[];mappedCount:number;filters:TowerFilters;onFilters:(next:TowerFilters)=>void;onHelp:(entry:ModelCase)=>void;onExplore:(id:string)=>void;onPreview:(entry:ModelCase)=>void;onClose:()=>void}) {
  const lang=useLanguage(),dialog=useRef<HTMLDialogElement>(null);const [query,setQuery]=useState('');
  useEffect(()=>{const previous=document.activeElement;dialog.current?.showModal();return()=>{dialog.current?.close();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};},[]);
  const rows=useMemo(()=>{const copy=getEditorial(lang).towers as Record<string,{name:string;label:string}>;const countries=new Intl.DisplayNames([lang],{type:'region'});return cases.map(entry=>({...entry,name:lang!=='zh-CN'?(entry.communityNameReviewed?entry.nameEn??entry.name:copy[entry.id]?.name??entry.nameEn??entry.name):entry.name,countryName:countries.of(entry.countryCode)??entry.countryCode})).filter(entry=>`${entry.name} ${entry.countryName} ${entry.id}`.normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').toLowerCase()));},[cases,lang,query]);
  return <dialog className="model-gallery" ref={dialog} aria-labelledby="model-gallery-title" onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}}><header><div><span className="eyebrow">WORLD ECHO · 3D COLLECTION</span><h2 id="model-gallery-title">{t('{0} 座建筑，选一座近看',cases.length)}</h2><p>{t('当前地图显示 {0} 个地点。大致位置已标注，可继续核对。',mappedCount)}</p></div><button aria-label={t('关闭')} onClick={onClose}><X size={22}/></button></header><div className="model-gallery-tools"><label className="model-gallery-search"><Search size={16}/><input type="search" value={query} placeholder={t('搜索国家、城市或模型')} aria-label={t('搜索国家、城市或模型')} onChange={event=>setQuery(event.target.value)}/></label><button className="model-library-all" onClick={()=>{setQuery('');onFilters({...DEFAULT_TOWER_FILTERS});}}>{t('全部模型')}</button><details className="gallery-filters"><summary><SlidersHorizontal size={14}/>{t('筛选铁塔')}{activeTowerFilters(filters)>0&&` · ${activeTowerFilters(filters)}`}</summary><TowerFilterFields filters={filters} onChange={onFilters}/></details></div><div className="model-gallery-grid">{rows.map(entry=><article key={entry.id}><button className="model-gallery-image" onClick={()=>onPreview(entry)} title={t('近看建筑')}><img src={entry.previewHash ? entry.previewUrl + "?v=" + entry.previewHash.slice(0,12) : entry.previewUrl} alt={t('{0}模型渲染',entry.name)} loading="lazy"/><span>{entry.modelContext==='inferred-completion'?(entry.modelCollection==='related'?t('相关建筑 · 含推测补全'):t('含推测补全')):entry.modelCollection==='other'?t('其他类型'):entry.modelCollection==='related'?t("相关建筑参考"):entry.modelCollection==='reference'?(entry.modelScope==='visible-section'?t("可见塔段参考"):t("外观参考")):entry.historicalAppearance?t("历史外观模型"):t("模型渲染")}</span></button><div><strong>{entry.name}</strong><small>{entry.countryName} · {entry.heightM===null?t('实际高度待核'):t('参考高度 {0}',formatMetres(entry.heightM,entry.heightApproximate??false,false,lang))}</small><div className="model-gallery-actions"><button onClick={()=>onPreview(entry)}><Cuboid size={13}/>{t('自由近看')}</button>{entry.hasMap?<button onClick={()=>{onClose();onExplore(entry.id);}}><Globe2 size={13}/>{t('地球探索')}</button>:<button className="model-help-link" onClick={()=>onHelp(entry)}><Flag size={12}/>{t('补充塔的位置')}</button>}</div></div></article>)}{!rows.length&&<p className="model-gallery-empty" role="status">{t('没有匹配的模型，可清除筛选或搜索。')}</p>}</div></dialog>;
}
